### ISSUE TITLE
crashes on startup

### ISSUE THREAD

**Issue by dysie** [radj307/volume-control#57] opened 2023-01-28 05:57 UTC
every time i try to open the application it crashes without opening. the preview version 6.0.0 opens fine but is completely blank as i assume its not finished.

im using windows 11 if that means anything. 

here is the full crash report: 

`////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

                             /// VOLUME CONTROL CRASH REPORT /// 21:55:20:385  [FATAL]   ///

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

HH:mm:ss:fff           === Log Initialized @ Saturday, January 28, 2023 5:55:18 AM ===  { Filter: 30 (ALL_EXCEPT_DEBUG) }
21:55:18:951  [INFO]   The version number in the settings file was 0.0.0, settings will be upgraded to 5.2.5.
21:55:20:347  [ERROR]  {
                         'Message': 'Process with an Id of 18864 is not running.'
                         'HResult': '-2147024809'
                         'Source': 'System.Diagnostics.Process'
                         'TargetSite': {
                           'Name': 'GetProcessById'
                           'DeclaringType': 'System.Diagnostics.Process'
                           'Attributes': 'PrivateScope, Public, Static, HideBySig'
                           'CallingConvention': 'Standard'
                         }
                         'StackTrace': {
                           [0] at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName)
                           [1] at System.Diagnostics.Process.GetProcessById(Int32 processId)
                           [2] at VolumeControl.Audio.AudioSession.GetProcess()
                         }
                       }
21:55:20:359  [ERROR]  The constructor of 'VolumeControl.Audio.AudioSession' encountered an error when getting process with ID '18864'!
21:55:20:359  [ERROR]  An unhandled exception occurred!
                         Sender: 'System.Windows.Threading.Dispatcher' (System.Windows.Threading.Dispatcher)
                       {
                         'Message': 'Exception has been thrown by the target of an invocation.'
                         'HResult': '-2146232828'
                         'Source': 'System.Private.CoreLib'
                         'TargetSite': {
                           'Name': 'CreateInstanceDefaultCtor'
                           'DeclaringType': 'System.RuntimeType'
                           'Attributes': 'PrivateScope, Assembly, HideBySig'
                           'CallingConvention': 'Standard, HasThis'
                         }
                         'Data':{
                           'System.Object': ''
                         }
                         'StackTrace': {
                           [0] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                           [1] at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
                           [2] at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
                           [3] at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
                           [4] at System.Activator.CreateInstance(Type type, Object[] args)
                           [5] at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
                           [6] at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
                           [7] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
                           [8] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
                           [9] at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
                           [10] at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
                           [11] at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
                           [12] at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
                           [13] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                           [14] at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
                           [15] at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
                           [16] at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
                           [17] at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
                           [18] at System.Windows.Application.DoStartup()
                           [19] at System.Windows.Application.<.ctor>b__1_0(Object unused)
                           [20] at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
                           [21] at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
                         }
                         'InnerException': {
                           'Message': 'Exception has been thrown by the target of an invocation.'
                           'HResult': '-2146232828'
                           'Source': 'System.Private.CoreLib'
                           'TargetSite': {
                             'Name': 'CreateInstanceDefaultCtor'
                             'DeclaringType': 'System.RuntimeType'
                             'Attributes': 'PrivateScope, Assembly, HideBySig'
                             'CallingConvention': 'Standard, HasThis'
                           }
                           'StackTrace': {
                             [0] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                             [1] at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
                             [2] at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
                             [3] at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
                             [4] at System.Activator.CreateInstance(Type type, Object[] args)
                             [5] at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
                             [6] at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
                             [7] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
                             [8] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
                             [9] at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
                             [10] at System.Xaml.XamlObjectWriter.WriteEndObject()
                             [11] at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
                             [12] at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
                             [13] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                             [14] at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
                             [15] at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
                             [16] at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
                             [17] at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
                             [18] at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
                             [19] at System.Windows.ResourceDictionary.FetchResource(Object resourceKey, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean canCacheAsThemeResource, Boolean& canCache)
                             [20] at System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object& source)
                             [21] at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [22] at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [23] at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [24] at System.Windows.StaticResourceExtension.TryProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [25] at System.Windows.StaticResourceExtension.ProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference)
                             [26] at System.Windows.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider)
                             [27] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
                             [28] at System.Xaml.XamlObjectWriter.Logic_ProvideValue(ObjectWriterContext ctx)
                             [29] at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
                             [30] at System.Xaml.XamlObjectWriter.WriteEndMember()
                             [31] at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
                             [32] at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
                             [33] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                             [34] at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
                             [35] at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
                             [36] at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
                             [37] at VolumeControl.Mixer.InitializeComponent()
                             [38] at VolumeControl.Mixer..ctor()
                             [39] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                           }
                           'InnerException': {
                             'Message': 'Object reference not set to an instance of an object.'
                             'HResult': '-2147467261'
                             'Source': 'VolumeControl.Audio'
                             'TargetSite': {
                               'Name': 'Dispose'
                               'DeclaringType': 'VolumeControl.Audio.AudioSession'
                               'Attributes': 'PrivateScope, Public, Final, Virtual, HideBySig, VtableLayoutMask'
                               'CallingConvention': 'Standard, HasThis'
                             }
                             'StackTrace': {
                               [0] at VolumeControl.Audio.AudioSession.Dispose()
                               [1] at VolumeControl.Audio.AudioSession..ctor(AudioSessionControl controller)
                               [2] at VolumeControl.Audio.AudioDevice.ReloadSessions()
                               [3] at VolumeControl.Audio.AudioDevice..ctor(MMDevice device)
                               [4] at VolumeControl.Audio.Collections.AudioDeviceCollection.CreateDeviceFromMMDevice(MMDevice mmDevice)
                               [5] at VolumeControl.Audio.Collections.AudioDeviceCollection.Reload(MMDeviceEnumerator enumerator)
                               [6] at VolumeControl.Audio.Collections.AudioDeviceCollection..ctor(AudioAPI api, DataFlow flow)
                               [7] at VolumeControl.Audio.AudioAPI..ctor()
                               [8] at VolumeControl.Helpers.VolumeControlSettings..ctor()
                               [9] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                             }
                           }
                         }
                       }
21:55:20:364  [FATAL]  App exited because of an unhandled exception!
                       {
                         'Message': 'Exception has been thrown by the target of an invocation.'
                         'HResult': '-2146232828'
                         'Source': 'System.Private.CoreLib'
                         'TargetSite': {
                           'Name': 'CreateInstanceDefaultCtor'
                           'DeclaringType': 'System.RuntimeType'
                           'Attributes': 'PrivateScope, Assembly, HideBySig'
                           'CallingConvention': 'Standard, HasThis'
                         }
                         'Data':{
                           'System.Object': ''
                         }
                         'StackTrace': {
                           [0] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                           [1] at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
                           [2] at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
                           [3] at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
                           [4] at System.Activator.CreateInstance(Type type, Object[] args)
                           [5] at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
                           [6] at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
                           [7] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
                           [8] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
                           [9] at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
                           [10] at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
                           [11] at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
                           [12] at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
                           [13] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                           [14] at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
                           [15] at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
                           [16] at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
                           [17] at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
                           [18] at System.Windows.Application.DoStartup()
                           [19] at System.Windows.Application.<.ctor>b__1_0(Object unused)
                           [20] at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
                           [21] at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
                           [22] at System.Windows.Threading.DispatcherOperation.InvokeImpl()
                           [23] at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
                           [24] at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
                           [25] at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                           [26] --- End of stack trace from previous location ---
                           [27] at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
                           [28] at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
                           [29] at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
                           [30] at System.Windows.Threading.DispatcherOperation.Invoke()
                           [31] at System.Windows.Threading.Dispatcher.ProcessQueue()
                           [32] at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
                           [33] at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
                           [34] at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
                           [35] at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
                           [36] at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
                           [37] at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
                           [38] at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
                           [39] at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
                           [40] at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
                           [41] at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
                           [42] at System.Windows.Threading.Dispatcher.Run()
                           [43] at System.Windows.Application.RunDispatcher(Object ignore)
                           [44] at System.Windows.Application.RunInternal(Window window)
                           [45] at System.Windows.Application.Run()
                           [46] at VolumeControl.Program.Main(String[] args)
                         }
                         'InnerException': {
                           'Message': 'Exception has been thrown by the target of an invocation.'
                           'HResult': '-2146232828'
                           'Source': 'System.Private.CoreLib'
                           'TargetSite': {
                             'Name': 'CreateInstanceDefaultCtor'
                             'DeclaringType': 'System.RuntimeType'
                             'Attributes': 'PrivateScope, Assembly, HideBySig'
                             'CallingConvention': 'Standard, HasThis'
                           }
                           'StackTrace': {
                             [0] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                             [1] at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
                             [2] at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
                             [3] at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
                             [4] at System.Activator.CreateInstance(Type type, Object[] args)
                             [5] at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
                             [6] at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
                             [7] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
                             [8] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
                             [9] at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
                             [10] at System.Xaml.XamlObjectWriter.WriteEndObject()
                             [11] at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
                             [12] at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
                             [13] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                             [14] at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
                             [15] at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value, Boolean& canCache)
                             [16] at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object& value, Boolean& canCache)
                             [17] at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean& canCache)
                             [18] at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
                             [19] at System.Windows.ResourceDictionary.FetchResource(Object resourceKey, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, Boolean canCacheAsThemeResource, Boolean& canCache)
                             [20] at System.Windows.FrameworkElement.FindResourceInternal(FrameworkElement fe, FrameworkContentElement fce, DependencyProperty dp, Object resourceKey, Object unlinkedParent, Boolean allowDeferredResourceReference, Boolean mustReturnDeferredResourceReference, DependencyObject boundaryElement, Boolean isImplicitStyleLookup, Object& source)
                             [21] at System.Windows.StaticResourceExtension.FindResourceInAppOrSystem(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [22] at System.Windows.StaticResourceExtension.FindResourceInEnviroment(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [23] at System.Windows.StaticResourceExtension.TryProvideValueImpl(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [24] at System.Windows.StaticResourceExtension.TryProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference, Boolean mustReturnDeferredResourceReference)
                             [25] at System.Windows.StaticResourceExtension.ProvideValueInternal(IServiceProvider serviceProvider, Boolean allowDeferredReference)
                             [26] at System.Windows.StaticResourceExtension.ProvideValue(IServiceProvider serviceProvider)
                             [27] at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
                             [28] at System.Xaml.XamlObjectWriter.Logic_ProvideValue(ObjectWriterContext ctx)
                             [29] at System.Xaml.XamlObjectWriter.Logic_AssignProvidedValue(ObjectWriterContext ctx)
                             [30] at System.Xaml.XamlObjectWriter.WriteEndMember()
                             [31] at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
                             [32] at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
                             [33] at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
                             [34] at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
                             [35] at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
                             [36] at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
                             [37] at VolumeControl.Mixer.InitializeComponent()
                             [38] at VolumeControl.Mixer..ctor()
                             [39] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                           }
                           'InnerException': {
                             'Message': 'Object reference not set to an instance of an object.'
                             'HResult': '-2147467261'
                             'Source': 'VolumeControl.Audio'
                             'TargetSite': {
                               'Name': 'Dispose'
                               'DeclaringType': 'VolumeControl.Audio.AudioSession'
                               'Attributes': 'PrivateScope, Public, Final, Virtual, HideBySig, VtableLayoutMask'
                               'CallingConvention': 'Standard, HasThis'
                             }
                             'StackTrace': {
                               [0] at VolumeControl.Audio.AudioSession.Dispose()
                               [1] at VolumeControl.Audio.AudioSession..ctor(AudioSessionControl controller)
                               [2] at VolumeControl.Audio.AudioDevice.ReloadSessions()
                               [3] at VolumeControl.Audio.AudioDevice..ctor(MMDevice device)
                               [4] at VolumeControl.Audio.Collections.AudioDeviceCollection.CreateDeviceFromMMDevice(MMDevice mmDevice)
                               [5] at VolumeControl.Audio.Collections.AudioDeviceCollection.Reload(MMDeviceEnumerator enumerator)
                               [6] at VolumeControl.Audio.Collections.AudioDeviceCollection..ctor(AudioAPI api, DataFlow flow)
                               [7] at VolumeControl.Audio.AudioAPI..ctor()
                               [8] at VolumeControl.Helpers.VolumeControlSettings..ctor()
                               [9] at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
                             }
                           }
                         }
                       }
`

**Comment by StormingChaos** [comment] 2023-02-03 02:06
This may have something to do with Windows 11, we are developing on Windows 10.

Gonna look into this issue but in the meantime, make sure you have .NET 6 installed.

**Comment by radj307** [comment] 2023-04-03 20:44
Are you still having issues with [6.0.0 Preview 5](https://github.com/radj307/volume-control/releases/6.0.0-pr5)?

**Comment by Jeremy2131** [comment] 2023-06-28 16:50
> Are you still having issues with [6.0.0 Preview 5](https://github.com/radj307/volume-control/releases/6.0.0-pr5)?

I tried 6.0.0 having the same problem as that guy and I don't see any UI

**Comment by radj307** [comment] 2023-08-12 20:20
From what I can tell, this issue mentions 2 different problems:
1. Crash on startup on version 5.X.X using Windows 11
2. UI is blank on version 6.X.X using Windows 11

Since the crash log mentions the constructor of `AudioSession` as the cause and we're currently in the process of entirely replacing that class (see #65), I'm going to close this.

Regarding the second problem of the UI being blank, please open a separate issue for that using the issue template for bugs (and include your log file).

**Closed by radj307** 2023-08-12 20:20 UTC
Labels: bug, cannot-replicate, needs-more-information

**Comment by radj307** [comment] 2023-08-12 20:35
See #71

**Comment by radj307** [comment] 2023-08-13 22:31
Cannot replicate either issue on Windows 11 Home 22H2 OS Build 22621.1702 virtual machine (Volume Control being the only thing installed)
