### ISSUE TITLE
[BUG] Refusing to launch

### ISSUE THREAD

**Issue by Austin12325** [radj307/volume-control#82] opened 2023-09-23 03:30 UTC
### Version

6.0.0

### Windows Version

Windows 11 Pro Version 22H2 (Build 22621.2134)

### Actual Behaviour

After attempting to launch, the program is terminated before opening (can be seen from the task manager). VolumeControl was installed using the 6.0.0 installer. (It will launch from Program Files if ran as administrator)

When moving the contents of VolumeControl to another folder ( I moved it to Documents) the program worked as expected and launched with no issue.

**Comment by radj307** [comment] 2023-09-23 21:27
Duplicate of #79

**Closed by radj307** 2023-09-23 21:27 UTC
Labels: bug, triage

**Comment by radj307** [comment] 2023-09-23 23:05
Should be fixed as of [v6.0.1](https://github.com/radj307/volume-control/releases/tag/6.0.1)

**Comment by radj307** [comment] 2023-10-01 17:41
This issue may have actually been present in v6.0.1 - v6.0.3 due to another issue with a CI script.  
It has been fixed in [v6.0.4](https://github.com/radj307/volume-control/releases/tag/6.0.4)
