### ISSUE TITLE
[BUG] Application sometimes does not start completely minimized

### ISSUE THREAD

**Issue by StormingChaos** [radj307/volume-control#27] opened 2022-07-28 16:44 UTC
### Version

5.2.0-rc*

### Actual Behaviour

Upon launching application with "start minimized" on, A minimized version pops up in the bottom left of my screen, I can click it to show the context menu, and double clicking, fully opens the volume control process. 

### Expected Behaviour

program should open silently and make you think, "wait did it actually open?" prompting you to show hidden items in your taskbar and realising, yes, it is open, it was sneaky like a good little background process

### Reproduction Steps

!. Turn on Start minimized
2. close application
3. open application
4. witness minimized title bar in bottom left

### Log

```shell
a bunch of stuff about how a 32 bit process cannot query information from a 64 bit process
```

**Comment by radj307** [comment] 2022-08-02 22:56
Cannot reproduce; closing unless someone else can.

**Closed by radj307** 2022-08-02 22:56 UTC
Labels: bug, triage
